### PR TITLE
Update README.md with CLI usage instructions

### PR DESCRIPTION
**Pull request by snuggs**
Documentation for Command Line Interface development.

_Some of us like package.json scripts_

Thanks so much. Look forward to contributing more!

### CODE REVIEW

**Comment by snuggs** [comment]
@jonathantneal #ping

**Comment by TrySound** [comment]
So much words for every package. Can't we just leave a reference to CLI readme?

**Comment by snuggs** [comment]
@TrySound this is true. Have just seen this in some of the plugins and some not. Doesn't seem to be a documenting convention on plugins. If we sit on the side of the fence of less code is more laziness then I'll close this PR.  As usual thanks for the input.

**Comment by jonathantneal** [comment]
I like this. I hope the docs can be simplified,  but I see this as a step forward. Thank you @snuggs !

**Pull request merged**
